version: '3.9'

services:
  frontend:
    build: ./client
    ports:
      - '5173:5173'
    depends_on:
      - backend
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aiteamboard
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  pgdata:
  redis_data:
