name: Continuous Deployment (CD)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Очищаем рабочую папку сервера, копируем свежий код и сразу запускаем Docker
      - name: Copy files and Deploy with Docker Compose
        run: |
          # 1. Копируем всё БЕЗ sudo(так как права у andre уже есть)
          cp -r . /var/www/soulbit/
          # 2. Переходим в целевую папку
          cd /var/www/soulbit/
          docker compose down --remove-orphans
          docker compose up --build -d